### ISSUE TITLE
beforeSave issues with dirtyKeys

### ISSUE THREAD

**Issue by Silkjaer** [ParsePlatform/CloudCode-Express#1]
I have a node.js server setup, registering webhooks etc.

Everything seems to run smooth, however in my beforeSave triggers I need to check if certain keys are dirty and they never are?

```
Parse.Cloud.beforeSave("CLASSNAME", function(request, response) {
	console.log(request.object.dirtyKeys()); // always outputs an empty array to the console
	if(request.object.dirty("key") && request.object.get("key")) { // value is a boolean
		// never executes
	}
});
```

Is this a bug, or am I doing something wrong?

**Comment by gfosco** [comment]
So, through webhooks, you won't be able to access that information.  https://parse.com/docs/js/guide#cloud-code-advanced-cloud-code-webhooks

This is something being considered as a feature change with the Parse API, to provide both the original and the update (not necessarily in the form of dirty keys, but you'd be able to determine that.)

Closing as it's not a module issue, but will be addressed if the API changes.
