### ISSUE TITLE
Better Readme with ngrok  

### ISSUE THREAD

**Issue by loftyet** [ParsePlatform/CloudCode-Express#10]
I think the readme about setting up ngrok is a little misleading.
In Readme, 
export HOOKS_URL=https://something.ngrok.io
Since there is no "/" at the end of the io. It will lead to the following url appeared in Parse Webhook dashboard
https://something.ngrok.iowebhook/fun_XXXXX

**Comment by gfosco** [comment]
Ok, I updated the readme with the trailing slash.  Thanks for the contribution!
