### ISSUE TITLE
Unable to edit request.object on beforeSave

### ISSUE THREAD

**Issue by huguesbr** [ParsePlatform/CloudCode-Express#6]
Hi,

I've run into an issue with `beforeSave` and cloud code running on `Heroku`.

It seem like `beforeSave` hook on `Heroku` can't edit the `request.object` properties before saving. 

I've created a `stackoverflow` question and report of similar issue using `Heroku`.

Any idea? Thanks

http://stackoverflow.com/questions/34044843/setting-some-parse-user-property-on-beforesave-when-running-on-heroku

**Comment by gfosco** [comment]
In a webhook, you need to pass back the object to the success handler.  Try:

`response.success(user);`

**Comment by huguesbr** [comment]
! oh my.. ! thx!

**Comment by huguesbr** [comment]
Doc should be update: https://parse.com/docs/cloudcode/guide#cloud-code-modifying-objects-on-save

**Comment by gfosco** [comment]
Those docs are targeted at the hosted cloud code product.  I'd rather update the readme on this project, or the parse-cloud-express module.  PRs welcome, or I'll get to it eventually.

**Comment by huguesbr** [comment]
@gfosco something like this? https://github.com/ParsePlatform/CloudCode-Express/pull/7

**Comment by huguesbr** [comment]
@gfosco any voodoo secret code for Facebook user?

```
Parse.Cloud.beforeSave("_User", function(request, response) {
  console.log('Ran beforeSave on a User: ' + request.object.get('objectId'));
  // https://parse.com/questions/difference-between-existed-and-isnew
  if(!request.object.isNew()) {
    console.log('existing user');
    response.success(); 
  } else {
    console.log('new user');
    request.object.set('xxx', 'yyy');
    response.success(request.object); 
  }
});
```

 :white_check_mark: Signing up with email/password. I see `new user` in log.
 :white_check_mark: Login with this email/password. I see `existing user` in log.
 :white_check_mark: Login up with a new Facebook user (using Parse UI LoginViewController on iOS). I see `new user` in log.
:x: Login with an existing Facebook user (using Parse UI LoginViewController on iOS). I see `new user` in log.

FYI, login with a Facebook user do the following Parse REST API call:

```
POST https://api.parse.com/1/users
{
	"authData": {
		"facebook": {
			"id": "xxx",
			"access_token": "xxx",
			"expiration_date": "2016-02-08T09:33:28.692Z"
		}
	}
}
```

Any idea?

**Comment by huguesbr** [comment]
@gfosco sorry to piggy back on this issue.. probably not related at all.. wish there was a repo for parse backend.. even just to submit issue...

**Comment by gfosco** [comment]
Please report this as a bug through parse.com/help (click the something wrong? contact us link) and be specific, that an existing facebook user login, when using a beforeSave hook on _User, is coming over as a new user.

**Comment by huguesbr** [comment]
Sure thing. Will do today. 

--
Hugues Bernet-Rollande




On Thu, Dec 10, 2015 at 3:24 PM -0800, "Fosco Marotto" <notifications@github.com> wrote:












Please report this as a bug through parse.com/help (click the something wrong? contact us link) and be specific, that an existing facebook user login, when using a beforeSave hook on _User, is coming over as a new user.

**Comment by huguesbr** [comment]
@gfosco https://developers.facebook.com/bugs/create/?parse_app_id=xxx&parse_app_name=xxx&parse_email=xxx doesn't seem to be functional. I can't select any sub category in it..
where do you report issue about bug reporting issue tool :)

**Comment by gfosco** [comment]
@huguesbr Hmm, it's working for me... are you logged in to fb?

**Comment by huguesbr** [comment]
yep.. my parse app is not link to any fb account.. I see the page but I just can't select any sub categories.. I will triple check..

**Comment by icanberk** [comment]
@huguesbr Ended up finding a solution for this? I'm having a similar problem.(also hosted on Heroku)

In my case, I get 'username can't be modified in _beforeSave' if the user is signed up through FB.

**Comment by huguesbr** [comment]
@icanberk, as @gfosco mention above, using webhook you have to pass back the object in the success handler.

`response.success(user);`

**Comment by huguesbr** [comment]
@gfosco and btw issue about bug report is due to using safari.. it work as expected using chrome... (sorry again for this polluted thread...)
